
version: "3"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'